Repository Louis-Matsika/kayan, pull requests merged in 2022-08, with the labels that each got.

#1 remove react png icons
  public/favicon.ico
  public/logo192.png
  public/logo512.png
Labels: good first issue, front end

#2 add basic homepage layout
  package-lock.json
  public/index.html
  public/site-content/logo-white-tick.png
  public/site-content/omologo.png
  public/site-content/toni_phases.png
  src/App.css
  src/pages/Home.js
  yarn.lock
Labels: enhancement, front end

#6 Feature development
  .firebase/hosting.YnVpbGQ.cache
Labels: back-end

#7 Frontend features
  .firebaserc
  firebase.json
  public/index.html
  public/site-content/logo-white-tick.png
  public/site-content/toni_phases.jpg
  public/site-content/toni_phases.png
  src/App-queries.css
  src/App.css
  src/App.js
  src/pages/Home.js
Labels: enhancement, front-end

#8 Frontend features
  .firebase/hosting.YnVpbGQ.cache
  public/site-content/off-white.jpg
  public/site-content/omologo-white.png
  src/App.css
  src/pages/Home.js
Labels: enhancement, front-end
